'use client';

import { ArrowRight, Bot, Building2, CheckCircle2, Factory, Gauge, MapPin, Network, Sparkles, University, Users } from 'lucide-react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { challenges } from '@/lib/mockData';
import { ChallengeCard, Reveal, SiteNav, StatKpi, TrustStrip } from '@/components/ui';

export default function Home(){
  return <>
    <SiteNav/>
    <main>
      <section className="hero grid-bg"><div className="container hero-grid"><div>
        <div className="eyebrow">SIH 26043 · SMART EDUCATION · JHARKHAND</div>
        <motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.65}}>From <span>community problems</span> to scalable solutions.</motion.h1>
        <p className="hero-copy">JharSetu turns unstructured societal challenges into actionable innovation projects — using AI to understand, prioritize and match them with the right universities, faculty and industry partners.</p>
        <div className="hero-actions"><Link className="btn btn-accent" href="/report">Report a challenge <ArrowRight size={16} style={{verticalAlign:'-3px'}}/></Link><Link className="btn btn-primary" href="/challenges">Explore the challenge map</Link></div>
        <TrustStrip/>
      </div><div className="orbit-card"><div className="eyebrow" style={{color:'#b9e86e'}}>The missing bridge</div><div style={{fontSize:28,fontWeight:800,lineHeight:1.05,marginTop:8,maxWidth:360}}>A complaint should be the beginning, not the end.</div><div className="orbit"><motion.div className="hub" animate={{scale:[1,1.03,1]}} transition={{duration:3,repeat:Infinity}}>AI Problem<br/>Intelligence<br/><span style={{fontSize:13,fontWeight:500}}>understand → route → activate</span></motion.div><div className="node n1"><strong>Citizen</strong>field signal</div><div className="node n2"><strong>University</strong>expertise + students</div><div className="node n3"><strong>Industry</strong>tools + pilots</div><div className="node n4"><strong>Government</strong>validate + scale</div></div></div></div></section>

      <section className="section"><div className="container"><Reveal><div className="section-head"><div><div className="eyebrow">System snapshot</div><h2>One network. Five stakeholders. One measurable outcome.</h2></div><Link href="/dashboard" className="btn btn-ghost">Open command centre</Link></div></Reveal>
        <div className="kpi-grid"><StatKpi label="Challenges" value="1,284" delta="+18% this month"/><StatKpi label="Validated" value="934" delta="72.7% of submissions"/><StatKpi label="Active projects" value="142" delta="41 in pilot"/><StatKpi label="People reached" value="1.8M" delta="estimated cumulative impact"/></div>
      </div></section>

      <section className="section" style={{paddingTop:0}}><div className="container"><Reveal><div className="section-head"><div><div className="eyebrow">Live challenge stream</div><h2>Problems worth solving</h2></div><Link className="btn btn-ghost" href="/challenges">View all</Link></div></Reveal><div className="challenge-grid">{challenges.slice(0,3).map(c=><ChallengeCard key={c.id} c={c}/>)}</div></div></section>

      <section className="section"><div className="container split"><Reveal><div className="card panel" style={{height:'100%'}}><div className="eyebrow">01 · AI problem intelligence</div><h2 style={{fontSize:42,letterSpacing:'-.05em',lineHeight:1.02}}>Turn messy human reports into structured challenge briefs.</h2><p className="muted" style={{lineHeight:1.7}}>Classification, severity, duplicate detection, impact scoring and explainable recommendations work together — with human validation before a challenge is routed.</p><div className="ai-box" style={{marginTop:20}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3>AI analysis · CH-1042</h3><Bot size={24}/></div><div className="ai-grid"><div className="ai-pill"><strong>Water</strong><small>Domain</small></div><div className="ai-pill"><strong>Critical</strong><small>Priority</small></div><div className="ai-pill"><strong>91 / 100</strong><small>Impact</small></div><div className="ai-pill"><strong>4 reports</strong><small>Likely duplicates</small></div></div></div></div></Reveal>
      <Reveal delay={.08}><div className="stack"><div className="card panel"><div className="eyebrow">02 · Intelligent matching</div><div style={{display:'flex',gap:14,alignItems:'center',marginTop:12}}><University size={26}/><div><strong>Problem → University → Faculty → Industry</strong><div className="muted" style={{fontSize:13,marginTop:4}}>Match by expertise, labs, location, capacity and prior relevance.</div></div></div></div><div className="card panel"><div className="eyebrow">03 · Lifecycle</div><div style={{marginTop:14}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8}}>{['Validate','Match','Prototype','Pilot','Measure','Scale'].map((x,i)=><div key={x} className="soft-card" style={{padding:'15px 12px'}}><div style={{font:'11px DM Mono',color:'var(--muted)'}}>0{i+1}</div><strong>{x}</strong></div>)}</div></div></div><div className="card panel"><div className="eyebrow">04 · Outcome registry</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginTop:14}}><div><div className="eyebrow">Pilots</div><strong style={{fontSize:28}}>41</strong></div><div><div className="eyebrow">Patents</div><strong style={{fontSize:28}}>12</strong></div><div><div className="eyebrow">Startups</div><strong style={{fontSize:28}}>8</strong></div></div></div></div></Reveal></div></section>

      <section className="section" style={{paddingTop:0}}><div className="container card panel"><div className="section-head"><div><div className="eyebrow">Design philosophy</div><h2>Human, editorial, public-sector ready.</h2></div><Sparkles size={26}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12}}>{[['No glassmorphism overload','Clean information hierarchy'],['AI with explanations','Recommendations show the why'],['Motion with purpose','State changes feel alive'],['Trust by design','Roles, evidence and audit trail']].map(([a,b])=><div className="soft-card" style={{padding:18}} key={a}><strong>{a}</strong><div className="muted" style={{fontSize:13,lineHeight:1.6,marginTop:6}}>{b}</div></div>)}</div></div></section>
    </main>
    <footer className="footer"><div className="container footer-grid"><div><div className="brand"><span className="brand-mark">J</span><span>JharSetu</span></div><p className="muted" style={{maxWidth:420,lineHeight:1.7}}>From community problems to scalable solutions. A prototype direction for SIH Problem Statement 26043.</p></div><div><h4>Product</h4><Link href="/report">Report a challenge</Link><Link href="/challenges">Explore challenges</Link><Link href="/dashboard">Government dashboard</Link></div><div><h4>Network</h4><Link href="/projects/PR-21">Projects</Link><Link href="/challenges/CH-1042">Water pilot</Link><Link href="/dashboard#partners">Partner registry</Link></div></div></footer>
  </>
}
