import { Challenge, Partner } from './types';

export const challenges: Challenge[] = [
  {
    id: 'CH-1042',
    title: 'Rural drinking water quality monitoring',
    summary: 'Residents across 11 villages report recurring water discoloration and odor near handpumps and local storage tanks.',
    domain: 'Water & Public Health',
    subcategory: 'Water Quality Monitoring',
    district: 'Dumka',
    location: 'Jarmundi, Dumka, Jharkhand',
    lat: 24.248, lng: 87.147,
    status: 'Matched',
    priority: 'Critical',
    impactScore: 91,
    affectedPeople: 1840,
    reports: 41,
    verified: true,
    submittedBy: 'Community Water Watch',
    createdAt: '2 days ago',
    expertise: ['Water Quality', 'IoT Sensors', 'Environmental Engineering', 'Public Health'],
    tags: ['water', 'rural', 'iot', 'health'],
  },
  {
    id: 'CH-1038',
    title: 'Monsoon access to primary health centre',
    summary: 'The last 4.5 km of a rural road becomes difficult for ambulances during heavy rain, delaying emergency care.',
    domain: 'Infrastructure',
    subcategory: 'Road Connectivity',
    district: 'Ranchi',
    location: 'Ormanjhi, Ranchi, Jharkhand',
    lat: 23.447, lng: 85.565,
    status: 'University Accepted',
    priority: 'High',
    impactScore: 86,
    affectedPeople: 920,
    reports: 17,
    verified: true,
    submittedBy: 'Gram Sabha – Ward 6',
    createdAt: '4 days ago',
    expertise: ['Civil Engineering', 'GIS', 'Transport', 'Healthcare Access'],
    tags: ['road', 'ambulance', 'monsoon'],
  },
  {
    id: 'CH-1024',
    title: 'Low-cost crop residue valorisation',
    summary: 'Small farmers need an affordable local solution to convert crop residue into value instead of burning it.',
    domain: 'Agriculture',
    subcategory: 'Waste & Circular Economy',
    district: 'Hazaribagh',
    location: 'Ichak, Hazaribagh, Jharkhand',
    lat: 24.39, lng: 85.289,
    status: 'Prototype',
    priority: 'High',
    impactScore: 82,
    affectedPeople: 5600,
    reports: 29,
    verified: true,
    submittedBy: 'Krishi Mitra Collective',
    createdAt: '1 week ago',
    expertise: ['Mechanical Engineering', 'AgriTech', 'Biomass', 'Climate'],
    tags: ['agriculture', 'biomass', 'farmers'],
  },
  {
    id: 'CH-1018',
    title: 'Accessible learning kiosks for remote schools',
    summary: 'Students in remote schools have irregular connectivity and limited access to digital learning content.',
    domain: 'Education',
    subcategory: 'Digital Learning',
    district: 'West Singhbhum',
    location: 'Chaibasa, Jharkhand',
    lat: 22.556, lng: 85.801,
    status: 'Validated',
    priority: 'Medium',
    impactScore: 76,
    affectedPeople: 1300,
    reports: 12,
    verified: true,
    submittedBy: 'School Management Committee',
    createdAt: '2 weeks ago',
    expertise: ['EdTech', 'Offline Computing', 'UX', 'Content Delivery'],
    tags: ['schools', 'education', 'offline'],
  },
  {
    id: 'CH-1007',
    title: 'Community solid-waste hotspot near market',
    summary: 'Unmanaged waste accumulates near a weekly market, attracting stray animals and creating drainage blockages.',
    domain: 'Environment',
    subcategory: 'Solid Waste',
    district: 'Bokaro',
    location: 'Chas, Bokaro, Jharkhand',
    lat: 23.64, lng: 86.17,
    status: 'Implemented',
    priority: 'Medium',
    impactScore: 69,
    affectedPeople: 870,
    reports: 33,
    verified: true,
    submittedBy: 'Market Traders Association',
    createdAt: '1 month ago',
    expertise: ['Waste Management', 'Computer Vision', 'Civic Operations'],
    tags: ['waste', 'market', 'drainage'],
  },
];

export const universityPartners: Partner[] = [
  { id: 'U-01', name: 'BIT Mesra — Water & Sustainability Lab', kind: 'University', match: 94, reason: ['Water quality research', 'IoT prototyping lab', '4 related projects'], capabilities: ['Water Quality', 'IoT', 'Environmental Engineering'] },
  { id: 'U-02', name: 'Central University of Jharkhand', kind: 'University', match: 89, reason: ['Environmental science faculty', 'Community field research', 'Incubation support'], capabilities: ['Environmental Science', 'GIS', 'Public Health'] },
  { id: 'U-03', name: 'Ranchi University Innovation Cell', kind: 'University', match: 83, reason: ['Strong student pool', 'Embedded systems lab', 'Innovation mentoring'], capabilities: ['Embedded Systems', 'AI', 'Student Teams'] },
];

export const facultyPartners: Partner[] = [
  { id: 'F-01', name: 'Dr. Ananya Sen', kind: 'Faculty', match: 92, reason: ['Water quality sensing', 'IoT field deployment'], capabilities: ['IoT Sensors', 'Water Quality', 'Field Research'] },
  { id: 'F-02', name: 'Dr. R. Kumar', kind: 'Faculty', match: 86, reason: ['Environmental risk modelling', 'GIS analytics'], capabilities: ['GIS', 'Environmental Analytics', 'Risk Modelling'] },
];

export const industryPartners: Partner[] = [
  { id: 'I-01', name: 'AquaSense Labs', kind: 'Industry', match: 91, reason: ['Low-cost water sensors', 'Pilot deployment team', 'Mentorship'], capabilities: ['Sensors', 'Hardware', 'Pilot Deployment'] },
  { id: 'I-02', name: 'GramTech Systems', kind: 'Industry', match: 86, reason: ['Rural connectivity', 'IoT gateways', 'CSR support'], capabilities: ['IoT', 'Connectivity', 'CSR Funding'] },
  { id: 'I-03', name: 'Metrica Analytics', kind: 'Industry', match: 79, reason: ['Data dashboards', 'Monitoring analytics'], capabilities: ['Data', 'Analytics', 'Cloud'] },
];
