'use client';
import { useState } from 'react';
import { ArrowRight, Bot, MapPin, UploadCloud } from 'lucide-react';
import Link from 'next/link';
import { SiteNav, TrustStrip } from '@/components/ui';

export default function Report(){ const [submitted,setSubmitted]=useState(false); const [text,setText]=useState('Our village water has started smelling and changing colour. Children and older residents are worried. There are multiple handpumps around the same area.');
 if(submitted) return <><SiteNav/><main className="section"><div className="container"><div className="card panel" style={{maxWidth:980,margin:'40px auto'}}><div className="ai-box"><div className="eyebrow" style={{color:'#b9e86e'}}>Submission received · CH-1057</div><h1 style={{fontSize:48,letterSpacing:'-.05em',margin:'10px 0'}}>The platform can start solving this problem now.</h1><p style={{color:'#c7d0c8',lineHeight:1.7}}>Your report has been converted into a structured challenge and ranked for the next workflow step.</p><div className="ai-grid"><div className="ai-pill"><strong>Water & Public Health</strong><small>AI category</small></div><div className="ai-pill"><strong>HIGH</strong><small>Priority</small></div><div className="ai-pill"><strong>88 / 100</strong><small>Impact score</small></div><div className="ai-pill"><strong>2 similar</strong><small>Potential duplicates</small></div></div></div><div className="split" style={{marginTop:16}}><div className="soft-card" style={{padding:20}}><div className="eyebrow">Recommended expertise</div><div className="tiny-list">{['Water Quality','Environmental Engineering','IoT Sensors','Public Health'].map(x=><span className="tiny" key={x}>{x}</span>)}</div></div><div className="soft-card" style={{padding:20}}><div className="eyebrow">Recommended next step</div><strong style={{fontSize:22}}>Match to solution partners</strong><p className="muted" style={{fontSize:13,lineHeight:1.6}}>The government validator can review the AI brief, then route the challenge to the highest-fit university and industry partners.</p></div></div><div style={{display:'flex',gap:10,marginTop:18}}><Link className="btn btn-accent" href="/challenges/CH-1042">See a live example</Link><Link className="btn btn-ghost" href="/dashboard">Open command centre</Link></div></div></div></main></>;
 return <><SiteNav/><main className="section"><div className="container"><div style={{maxWidth:840}}><div className="eyebrow">Citizen / community intake</div><h1 style={{fontSize:62,letterSpacing:'-.06em',lineHeight:.95,margin:'10px 0'}}>Report the problem.<br/><span style={{color:'var(--accent-2)'}}>We’ll build the bridge.</span></h1><p className="muted" style={{fontSize:17,lineHeight:1.75}}>Describe the challenge in your own words. JharSetu converts it into a structured brief for validation, matching and solution development.</p></div><div className="card panel" style={{marginTop:28}}><div className="form-grid"><div className="field full"><label>Challenge title</label><input defaultValue="Rural drinking water quality monitoring"/></div><div className="field full"><label>What is happening?</label><textarea value={text} onChange={e=>setText(e.target.value)}/></div><div className="field"><label>Location</label><div style={{display:'flex',gap:8}}><input defaultValue="Jarmundi, Dumka, Jharkhand"/><button className="btn btn-ghost" type="button" title="Use map"><MapPin size={16}/></button></div></div><div className="field"><label>Approx. people affected</label><input defaultValue="1800" type="number"/></div><div className="field"><label>Urgency</label><select defaultValue="High"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div><div className="field"><label>Category (optional)</label><select defaultValue="Water"><option>Water</option><option>Healthcare</option><option>Infrastructure</option><option>Education</option><option>Agriculture</option><option>Environment</option><option>Other</option></select></div><div className="field full"><label>Evidence</label><div className="soft-card" style={{padding:24,display:'flex',alignItems:'center',gap:14}}><UploadCloud size={22}/><div><strong>Drop photos, video or supporting documents</strong><div className="muted" style={{fontSize:13}}>Prototype storage is mocked; the submission flow remains functional.</div></div></div></div></div><TrustStrip/><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:18,marginTop:24}}><div className="muted" style={{fontSize:12,display:'flex',gap:8,alignItems:'center'}}><Bot size={16}/> AI recommendations are advisory until a human validator approves them.</div><button className="btn btn-primary" onClick={()=>setSubmitted(true)}>Submit & analyse <ArrowRight size={16} style={{verticalAlign:'-3px'}}/></button></div></div></div></main></> }
